name: healthcare-qlora
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - pip
  - git
  - pip:
    - transformers>=4.35.0
    - datasets>=2.14.0
    - accelerate>=0.24.0
    - peft>=0.6.0
    - bitsandbytes>=0.41.0
    - trl>=0.7.0
    - azure-ai-ml>=1.11.0
    - azure-identity>=1.15.0
    - azure-storage-blob>=12.19.0
    - azure-keyvault-secrets>=4.7.0
    - azureml-core>=1.54.0
    - azureml-train>=1.54.0
    - azureml-train-core>=1.54.0
    - botbuilder-core>=4.15.0
    - botbuilder-schema>=4.15.0
    - botbuilder-integration-aiohttp>=4.15.0
    - aiohttp>=3.8.0
    - azure-healthinsights-clinicalmatching>=1.0.0
    - azure-healthcareapis-fhir>=1.0.0
    - pandas>=2.0.0
    - numpy>=1.24.0
    - scikit-learn>=1.3.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - wandb>=0.16.0
    - evaluate>=0.4.0
    - rouge-score>=0.1.2
    - bleu>=0.7.0
    - python-dotenv>=1.0.0
    - pyyaml>=6.0
    - click>=8.1.0
    - tqdm>=4.65.0
    - loguru>=0.7.0
    - pytest>=7.4.0
    - black>=23.9.0
    - flake8>=6.1.0
    - mypy>=1.6.0
    - pre-commit>=3.4.0
    - jupyter>=1.0.0
    - ipykernel>=6.25.0